home/urls.py
from django.urls import include, path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('test/', views.home, name='home'),
]

listings/urls.py
from django.urls import include, path

from . import views

app_name = 'listings'
urlpatterns = [
    # /listings
    path('', views.IndexView.as_view(), name="index"),
    # /listings/1
    path('<int:pk>', views.DetailView.as_view(), name='detail_rev'),
    # /listings/1/date
    path('<int:pk>/<str:order>', views.DetailView.as_view(), name='detail'),
    path('<int:listing_id>/review/', views.review, name='review'),
    path('addlisting/', views.listing_view, name='add')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('login.urls')),
    path('listings/', include('listings.urls', namespace='listing'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Listing(models.Model):
    # long & lat are for gps coords
    # longitude = models.FloatField()
    # latitude = models.FloatField()

    address = models.CharField(max_length=250)
    name = models.CharField(max_length=100, default='NO_NAME')
    is_house = models.BooleanField()  # 0 = apt, 1 = house

    # amenities
    aircon = models.BooleanField(default=False)
    furnished = models.BooleanField(default=False)
    has_pool = models.BooleanField(default=False)
    pets_allowed = models.BooleanField(default=False)
    has_gym = models.BooleanField(default=False)
    unit_laundry = models.BooleanField(default=False)
    shared_laundry = models.BooleanField(default=False)

    rating = models.FloatField()  # average of ratings from reviews

    rent = models.IntegerField()  # in $
    beds = models.IntegerField(default=0)
    baths = models.IntegerField(default=0)
    desc = models.TextField(default='NO_DESCRIPTION')  # description of listing
    link = models.URLField(max_length=100, default='NO_LINK')

    lat = models.DecimalField(default=0, decimal_places=7, max_digits=10)
    lon = models.DecimalField(default=0, decimal_places=7, max_digits=10)

    # dateListed = models.DateTimeField()

    def __str__(self):
        return self.name

    # possible methods: was_listed_recent


class ListingImage(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')


class Review(models.Model):
    user = models.CharField(max_length=100, default='anonymous')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    date = models.DateTimeField('date posted', default=timezone.now)
    rating = models.IntegerField()  # will need some kind of validation system so input is 1-5
    # ratings maybe should be able to be submitted without a write-up. like just a star rating
    # if we do this, we should then only display reviews with non-empty review_text fields
    # but use all of them for calculating the average rating
    review_text = models.CharField(max_length=10000)

    def __str__(self):
        return self.review_text

listings/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
from crispy_forms.bootstrap import FormActions
from django import forms
from django.forms import ModelForm
from .models import Listing, Review

RATINGS = [tuple([x, x]) for x in range(1, 6)]


class ReviewForm(forms.Form):
    rating = forms.CharField(widget=forms.Select(choices=RATINGS))
    review = forms.CharField(widget=forms.Textarea)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Field('rating', rows="1"),
        Field('review', rows="5", css_class='input-xlarge'),
        FormActions(
            Submit('submit', 'Submit', css_class="btn-primary"),
            Submit('cancel', 'Cancel', css_class="btn-secondary", formnovalidate='formnovalidate'),
        )
    )


class ListingForm(ModelForm):
    """
    address = forms.CharField(widget=forms.Textarea)
    name = forms.CharField(widget=forms.Textarea)
    is_house = forms.BooleanField()  # 0 = apt, 1 = house
    rating = forms.FloatField()  # average of ratings from reviews
    rent = forms.IntegerField()  # in $
    beds = forms.IntegerField(default=0)
    baths = forms.IntegerField(default=0)
    desc = forms.CharField(widget=forms.Textarea)  # description of listing
    link = forms.URLField(widget=forms.Textarea)
    lat = forms.DecimalField(default=0)
    lon = forms.DecimalField(default=0)
    """

    class Meta:
        model = Listing
        fields = ['address', 'name', 'is_house', 'aircon', 'furnished', 'has_pool', 'pets_allowed', 'has_gym',
                  'unit_laundry', 'shared_laundry', 'rating', 'rent', 'beds', 'baths', 'desc', 'link']

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Field('address', rows="1"),
        Field('name', rows="1"),
        Field('is_house', rows="1"),
        Field('aircon', rows="1"),
        Field('furnished', rows="1"),
        Field('has_pool', rows="1"),
        Field('pets_allowed', rows="1"),
        Field('has_gym', rows="1"),
        Field('unit_laundry', rows="1"),
        Field('shared_laundry', rows="1"),
        Field('rating', rows="1"),
        Field('rent', rows="1"),
        Field('beds', rows="1"),
        Field('baths', rows="1"),
        Field('desc', rows="5", css_class='input-xlarge'),
        Field('link', rows="1"),
        FormActions(
            Submit('submit', 'Submit', css_class="btn-primary"),
            Submit('cancel', 'Cancel', css_class="btn-secondary", formnovalidate='formnovalidate'),
        )
    )

listings/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import requests

from django.views import generic
from .models import Listing, Review
from .forms import ReviewForm, ListingForm

GEOCODING_API_KEY = 'AIzaSyB_AAHgx8qJADN8uk1N2Qa_qcDLxm21054'

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'listings/index.html'
    context_object_name = 'listing_list'

    def get_queryset(self):
        return Listing.objects.order_by('-rating')


class DetailView(generic.DetailView):
    model = Listing
    template_name = 'listings/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'order' in self.kwargs:
            context['order'] = self.kwargs['order']
        else:
            context['order'] = 'date'
        return context

    def get_queryset(self):
        # no special filtering here
        return Listing.objects.all()


def review(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    form = ReviewForm(request.POST)
    if 'cancel' in request.POST:
        return HttpResponseRedirect(reverse('listings:detail_rev', kwargs={'pk': listing_id}))

    if form.is_valid():
        rev = Review()
        if request.user.username != '':
            rev.user = request.user.username
        rev.listing = listing
        rev.rating = form.cleaned_data['rating']
        rev.review_text = form.cleaned_data['review']
        rev.save()

        reviews = Review.objects.filter(listing_id=listing.id)
        num = 0
        rating = 0
        for review in reviews:
           num += 1
           rating += review.rating 

        setattr(listing, "rating", rating/num)
        listing.save()

        return HttpResponseRedirect(reverse('listings:detail_rev', kwargs={'pk': listing_id}))
    else:
        form = ReviewForm()

    return render(request, 'listings/review.html', {
        'listing': listing,
        'form': form
    })


def listing_view(request):
    form = ListingForm(request.POST)
    if 'cancel' in request.POST:
        return HttpResponseRedirect(reverse('listings:index'))

    if form.is_valid():
        listing = Listing()

        listing.address = form.cleaned_data['address']
        listing.name = form.cleaned_data['name']
        listing.is_house = form.cleaned_data['is_house']
        listing.aircon = form.cleaned_data['aircon']
        listing.furnished = form.cleaned_data['furnished']
        listing.has_pool = form.cleaned_data['has_pool']
        listing.pets_allowed = form.cleaned_data['pets_allowed']
        listing.has_gym = form.cleaned_data['has_gym']
        listing.unit_laundry = form.cleaned_data['unit_laundry']
        listing.shared_laundry = form.cleaned_data['shared_laundry']
        listing.rating = form.cleaned_data['rating']
        listing.rent = form.cleaned_data['rent']
        listing.beds = form.cleaned_data['beds']
        listing.baths = form.cleaned_data['baths']
        listing.desc = form.cleaned_data['desc']
        listing.link = form.cleaned_data['link']

        geo_request = {'key': GEOCODING_API_KEY, 'address': listing.address}
        geocode_url = 'https://maps.googleapis.com/maps/api/geocode/json?'

        geo_resp = requests.get(geocode_url, params=geo_request).json()
        if geo_resp['status'] == 'OK':
            lat = geo_resp['results'][0]['geometry']['location']['lat']
            lon = geo_resp['results'][0]['geometry']['location']['lng']

        listing.lat = lat
        listing.lon = lon

        listing.save()

        return HttpResponseRedirect(reverse('listings:index'))
    else:
        form = ListingForm()

    return render(request, 'listings/addlisting.html', {'form': form})

listings/templates/listings/addlisting.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<form action="{% url 'listings:add' %}" method="post">
  {% csrf_token %}
    <legend><h1>Add Listing</h1></legend>
  {% crispy form %}
</form>
{% endif %}
{% endblock %} 

listings/templates/listings/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'home/stars.css' %}">

<script src='https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.css' rel='stylesheet'/>
<link rel="stylesheet" type="text/css" href="{% static 'listings/maps.css' %}">

  <legend><h1>Learn more about {{ listing.name }}</h1></legend>

  {% if listing.listingimage_set.all %}
  <h2>Photos</h2>
  <div class="row mb-3 h-25">
  {% for img in listing.listingimage_set.all %}
    <div class="col">
      <img alt="" src="{{ img.image.url }}" class="img-responsive mw-100" >
    </div>
  {% endfor %}
  </div>
  {% endif %}

  <h2>Description</h2>
  <div class="row mb-3">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <p>{{ listing.desc }}</p>
      <a href={{ listing.link }}>Looking for more information about this listing?</a>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Number of bedrooms
        <span class="badge bg-primary rounded-pill">{{ listing.beds }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Number of bathrooms
        <span class="badge bg-primary rounded-pill">{{ listing.baths }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Rent (per month)
        <span class="badge bg-primary rounded-pill">${{ listing.rent }}</span>
      </li>
    </ul>
    </div>
  </div>

  <h2>Location</h2>
  <div class="mb-3 h-25">
    <div id='map' style='width: 100%; height: 400px;'></div>
      <script>
      let lon = {{ listing.lon }};
      let lat = {{ listing.lat }};
      let name = "{{ listing.name }}"
      let addr = "{{ listing.address }}"
      </script>

      <script>
      mapboxgl.accessToken = 'pk.eyJ1Ijoic2FtY3Jvd24iLCJhIjoiY2t2dmRmcTliOHN5dTJxbXNrend2MWhmZCJ9.VMirb5Wp09qyL6VhqFWeIw';
      let map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/satellite-streets-v10',
        center: [lon, lat],
        zoom: 16
      });

      map.scrollZoom.disable()
      map.addControl(new mapboxgl.NavigationControl());

      // more markers can be added here, i.e. library
      const geojson = {
        type: 'FeatureCollection',
        features: [
          {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [lon, lat]
            },
            properties: {
              title: name,
              description: addr
            }
          }
        ]
      };

      // add markers to map
      for (const feature of geojson.features) {
        // create a HTML element for each feature
        const el = document.createElement('div');
        el.className = 'marker';

        // make a marker for each feature and add to the map
        new mapboxgl.Marker(el)
        .setLngLat(feature.geometry.coordinates)
        .setPopup(
          new mapboxgl.Popup({ offset: 25 }) // add popups
            .setHTML(
              `<h3>${feature.properties.title}</h3><p>${feature.properties.description}</p>`
            )
        )
        .addTo(map);
        }
    </script>
  </div>

  <div class="row">
    <div class="col mb-2">
      <h1>Reviews for {{ listing.name }}</h1>
    </div>
    <div class="col">
      <div class="dropdown">
      <button class="btn pull-right btn-secondary dropdown-toggle mt-1" role="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sort by
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="sortDropdown">
        <a class="dropdown-item" href={% url 'listing:detail' listing.id 'date' %}>Date</a>
        <a class="dropdown-item" href={% url 'listing:detail' listing.id 'rating' %}>Rating</a>
      </div>
    </div>
    </div>
  </div>

<div id="reviews">
  {% if listing.review_set.all %}
    {% for review in listing.review_set.all|dictsortreversed:order%}
      {% if review.rating == 5 %}
        <div class="card text-white bg-primary mb-3" style="max-width: 100rem;">
      {% endif %}
      {% if review.rating == 3 or review.rating == 4 %}
        <div class="card text-white bg-info mb-3" style="max-width: 100rem;">
      {% endif %}
      {% if review.rating == 1 or review.rating == 2 %}
        <div class="card text-white bg-danger mb-3" style="max-width: 100rem;">
      {% endif %}

        <div class="card-header">
          <span class="left">{{ review.user }}</span>
          <span class="right">{{ review.date }}</span>
        </div>
        <div class="card-body">
          <h4 class="card-title">Rating: {{ review.rating }}
            {% for i in "s"|rjust:review.rating %}
              <span class="fa fa-star checked"></span>
            {% endfor %}
          </h4>
          <p class="card-text">{{ review.review_text }}</p>
        </div>
        </div>
    {% endfor %}

{% else %}
    <p>No reviews are available.</p>
{% endif %}

{% if user.is_authenticated %}
  <a class="btn btn-primary" href="{% url 'listings:review' listing.id%}">Submit a review</a>
{% endif %}

{% endblock %}

listings/templates/listings/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'home/stars.css' %}">

  <legend><h1>Here's what we found:</h1></legend>
{% if listing_list %}
  <div class="row">
    {% for listing in listing_list %}
      <div class="col-lg-3 d-flex align-items-stretch">
      <div class="card text-white bg-primary mb-3 w-100" style="max-width: 20rem;">
      {% if listing.is_house%}
        <div class="card-header">house</div>
      {% else %}
        <div class="card-header">apartment</div>
      {% endif %}

      <div class="card-body d-flex flex-column">
      <h4 class="card-title">{{ listing.name }}</h4>
      <p class="card-text">${{ listing.rent }}/month</p>
        <p class="card-text">Avg: {{listing.rating|floatformat }}
        {% for i in "s"|rjust:listing.rating %}
          <span class="fa fa-star checked"></span>
        {% endfor %}
        </p>
        <a href="{% url 'listings:detail' listing.id 'date' %}" class="btn mt-auto btn-secondary stretched-link">More Info</a>
      </div>
      </div>
      </div>
    {% endfor %}
  </div>
{% else %}
    <p>No listings are available.</p>
{% endif %}
{% endblock %}

listings/templates/listings/review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<form action="{% url 'listings:review' listing.id%}" method="post">
  {% csrf_token %}
    <legend><h1>{{ listing.address }}</h1></legend>
  {% crispy form %}
</form>
{% endif %}
{% endblock %}